import type { Resume } from "@/domain/document/entities/Resume";

/**
 * ResumeContent — the structured JSON stored in Resume.content.
 *
 * Why store as JSON and not as rendered text?
 * Because the same data can be rendered in multiple formats (HTML,
 * plain text, PDF) and fed back to the AI for refinement without
 * re-generating from scratch. A text blob locks you in.
 *
 * Gemini is given this schema in the prompt so it generates
 * output that maps exactly to this shape.
 */
export interface ResumeContent {
  summary: string;
  experience: {
    company: string;
    position: string;
    location?: string;
    startDate: string;
    endDate: string;
    bullets: string[];
  }[];
  skills: {
    category: string;
    items: string[];
  }[];
  education: {
    institution: string;
    degree: string;
    year?: string;
  }[];
  projects?: {
    name: string;
    description: string;
    technologies: string[];
    url?: string | null;
  }[];
  /** Actionable ATS-improvement tips from the deterministic post-generation scorer (see AtsScorer.ts). */
  atsTips?: string[];
  /** Per-section show/hide toggles set from the editor — lets a section's data stay saved without being rendered. Missing key defaults to visible. */
  sectionVisibility?: { projects?: boolean };
}

/** Contact info provided by the user — not generated by Gemini */
export interface ResumeContact {
  email?: string;
  phone?: string;
  linkedin?: string;
  portfolio?: string;
  location?: string;
}

// ─── DTO ─────────────────────────────────────────────────────────────────────

export interface ResumeDTO {
  id: string;
  type: string;
  title: string;
  targetRole?: string;
  language: string;
  content: ResumeContent;
  contact: ResumeContact;
  atsScore?: number;
  createdAt: string;
}

export function toResumeDTO(resume: Resume): ResumeDTO {
  return {
    id: resume.id,
    type: resume.type,
    title: resume.title,
    targetRole: resume.targetRole,
    language: resume.language,
    content: resume.content as ResumeContent,
    contact: resume.contact as ResumeContact,
    atsScore: resume.atsScore,
    createdAt: resume.createdAt.toISOString(),
  };
}

// ─── Plain text export ────────────────────────────────────────────────────────

/**
 * Converts ResumeContent to clean plain text.
 * Used for clipboard copy and ATS compatibility.
 */
export function resumeToPlainText(
  content: ResumeContent,
  contact: ResumeContact,
  name: string,
): string {
  const lines: string[] = [];

  lines.push(name.toUpperCase());
  const contactParts = [contact.location, contact.email, contact.phone, contact.linkedin, contact.portfolio].filter(Boolean);
  if (contactParts.length) lines.push(contactParts.join(" | "));
  lines.push("");

  lines.push("PROFESSIONAL SUMMARY");
  lines.push("─".repeat(50));
  lines.push(content.summary);
  lines.push("");

  if (content.experience.length) {
    lines.push("EXPERIENCE");
    lines.push("─".repeat(50));
    for (const exp of content.experience) {
      lines.push(`${exp.company}  |  ${exp.startDate} – ${exp.endDate}`);
      lines.push(`${exp.position}${exp.location ? `  |  ${exp.location}` : ""}`);
      for (const bullet of exp.bullets) lines.push(`• ${bullet}`);
      lines.push("");
    }
  }

  if (content.skills.length) {
    lines.push("SKILLS");
    lines.push("─".repeat(50));
    for (const group of content.skills) lines.push(`${group.category}: ${group.items.join(", ")}`);
    lines.push("");
  }

  if (content.projects?.length && content.sectionVisibility?.projects !== false) {
    lines.push("PROJECTS");
    lines.push("─".repeat(50));
    for (const project of content.projects) {
      lines.push(`${project.name}`);
      lines.push(project.description);
      if (project.technologies.length) lines.push(`Technologies: ${project.technologies.join(", ")}`);
      if (project.url) lines.push(project.url);
      lines.push("");
    }
  }

  if (content.education.length) {
    lines.push("EDUCATION");
    lines.push("─".repeat(50));
    for (const edu of content.education) {
      lines.push(`${edu.institution}${edu.year ? `  (${edu.year})` : ""}`);
      lines.push(edu.degree);
      lines.push("");
    }
  }

  return lines.join("\n");
}
